version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - '${HTTP_PORT}:80'
    volumes:
      - ./:/app
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/log:/var/log/container/
    depends_on:
      - php

  php:
    build: ./docker/php
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/log:/var/log/container
    environment:
      XDEBUG_REMOTE_ENABLE: ${DOCKER_XDEBUG_REMOTE_ENABLE}
      XDEBUG_REMOTE_AUTOSTART: ${DOCKER_XDEBUG_REMOTE_AUTOSTART}
      XDEBUG_REMOTE_HOST: ${DOCKER_XDEBUG_REMOTE_HOST}
      XDEBUG_REMOTE_PORT: ${DOCKER_XDEBUG_REMOTE_PORT}
      XDEBUG_IDEKEY: ${DOCKER_XDEBUG_IDEKEY}
      XDEBUG_REMOTE_CONNECT_BACK: ${DOCKER_XDEBUG_REMOTE_CONNECT_BACK}
      PHP_IDE_CONFIG: ${DOCKER_PHP_IDE_CONFIG}
